  
name: test_pr

on: 
  push: 
    branches: [ develop ]
  pull_request:
    branches: [develop]
jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print 
        run: echo Working on develop
