  
name: Main Workflow

on: 
  push: 
    branches: [ main ]

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print 
        run: echo Working on Main Branch for conflict check.
